### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by Prithwi32** [JiyaGupta-cs/ShopNex#1]

**Comment by Prithwi32** [comment]
@JiyaGupta-cs  Please could you assign this task to me

**Comment by prasukjain07** [comment]
I also want to contribute in this
Please assign this task to me

**Comment by MaruthiSingh** [comment]
I would like to work on that issue under JWOC

**Comment by Sruti-sahini** [comment]
Hello @JiyaGupta-cs 
I have a good hold in web development.
Could you please assign me this issue after the coding periods starts?
I am from JWoC'24

**Comment by Prithwi32** [comment]
Hello @JiyaGupta-cs  I would like to work on that issue under JWOC ...
I ensure that to contribute responsiveness for the website, Thank You!

**Comment by prasukjain07** [comment]
> I also want to contribute in this
> Please assign this task to me 
> 

Under JWoC

**Comment by JiyaGupta-cs** [comment]
@Prithwi32 Are you working on it?

**Comment by Prithwi32** [comment]
> @Prithwi32 Are you working on it?

Hello.. Sir I will work on it.. How many days I have from today....as before the label were not added.. I thought it was under JWOC or not .   ...I will complete asap  ... Thank you!

**Comment by JiyaGupta-cs** [comment]
@Prithwi32 Are you working on it?

**Comment by Prithwi32** [comment]
> @Prithwi32 Are you working on it?

Yes...I will submit it by today

**Comment by Prithwi32** [comment]
https://github.com/JiyaGupta-cs/ShopNex/assets/115262737/fe8fef72-69b4-4ae2-9772-9bf647364e33

@JiyaGupta-cs Made responsive for I phone..check this once
