### ISSUE TITLE
[Enhancement]: add spacing in cards

### ISSUE THREAD

**Issue by Anushkabh** [JiyaGupta-cs/ShopNex#100]
## Issue Description
Beautify the products page , add some padding margin

## Screenshots
[Include any relevant screenshots]
![Screenshot (114)](https://github.com/JiyaGupta-cs/ShopNex/assets/99523033/a413f3a5-a144-4376-9ec6-b560a63c32ee)

**Comment by Anushkabh** [comment]
kindly assign me this issue under JWOC'24 @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Anushkabh Kindly grab major issues
