### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by ayesha-2101** [JiyaGupta-cs/ShopNex#11]
@JiyaGupta-cs I would like to create a login page for the website. Please assign it to me under JWOC

**Comment by JiyaGupta-cs** [comment]
@ayesha-2101
Go ahead and make sure you follow the contributing.md
And also follow the color and looks of the current template of the website

**Comment by JiyaGupta-cs** [comment]
@ayesha-2101 Are you working on it?

**Comment by ayesha-2101** [comment]
yes. I will raise the pr today

**Comment by Divyanshgarg-04** [comment]
@JiyaGupta-cs I would love to work on this issue under JWOC. Can you please assign this issue to me.

**Comment by Kpallavi5** [comment]
is this issue resolved? if not i would like to contribute on this this issue .

**Comment by JiyaGupta-cs** [comment]
@ayesha-2101 
Duplicate the Sign-Up page And Name it Login Page

**Comment by vishal2005025** [comment]
Mam, I would like to work on this issue.
Please assign it to me under JWOC'2024.

**Comment by JiyaGupta-cs** [comment]
@ayesha-2101 Are you working on it?

**Comment by vishal2005025** [comment]
Mam, I would like to work on this issue.
Please assign it to me under JWOC'2024.

**Comment by vishal2005025** [comment]
Please assign it to me under JWOC'2024.

**Comment by JiyaGupta-cs** [comment]
@vishal2005025 assigning it to you
And removing @ayesha-2101 due to inactivity
