### ISSUE TITLE
Add Sort Feature

### ISSUE THREAD

**Issue by JiyaGupta-cs** [JiyaGupta-cs/ShopNex#12]
Currently, the sort buttons on the product category page are not working
Make a sort feature that sorts the products according to Price with options of Low to High and High To Low

**Comment by amanswarnakar** [comment]
Hey @JiyaGupta-cs, please assign this issue to me under JWOC'24.

**Comment by sp-gits** [comment]
I would like to work on this issue under JWOC

**Comment by Jenis07** [comment]
Can you assign me this issue under JWOC?

**Comment by JiyaGupta-cs** [comment]
@amanswarnakar Assigning it to you

**Comment by amanswarnakar** [comment]
Hey @JiyaGupta-cs, I have created a PR for the feature. Please check once.
