### ISSUE TITLE
Sign in options

### ISSUE THREAD

**Issue by gaurijoshi25** [JiyaGupta-cs/ShopNex#123]
In the website under sign in there is no options for sign in with google, facebook etc..

we can do this by using oAuth library
please assign me this task under GSsoc'24 contributions

**Comment by Nayan-95** [comment]
Can you please assign me this issue.

**Comment by n14rishitha** [comment]
hi @JiyaGupta-cs

I would like to work on this issue . so please assign this task to me under the label GSSoC'24

**Comment by Priyagohite** [comment]
I would like to resolve this issue can you assign to me.
