### ISSUE TITLE
Enhancement of Footer UI

### ISSUE THREAD

**Issue by AlaynaShaheen** [JiyaGupta-cs/ShopNex#124]
## Issue Description
The links in the footer aren't properly aligned and the spaces aren't given correctly.

## Steps to Reproduce
We can align the 3 rows into 3 columns and can divide them into sections making it more visually appealing. Then we can remove extra spaces to enhance the interface.

## Expected Behavior
All the links in the footer are expected to be perfectly aligned according to their sections

## Actual Behavior
The UI looks quite improper as there is much spacing around each link in footer

## Screenshots

![Screenshot 2024-05-10 090839](https://github.com/JiyaGupta-cs/ShopNex/assets/111679498/0e3af03c-66df-4137-bd22-a5bc9b1af5cb)

**Comment by AlaynaShaheen** [comment]
Hello JiyaGupta,

I am a contributor participating in GSSoC'24. I want to enhance the footer UI to make it look more appealing to the users. I'm eager to tackle this challenge and contribute to the project. Please assign this issue to me. Looking forward on your guidance on how to proceed. 

Regards,
Alayna Shaheen

**Comment by Sushilverma002** [comment]
@AlaynaShaheen they are properly gaped and centered. please work on some other issue.
