### ISSUE TITLE
Sign In options using firebase and improve existing UI

### ISSUE THREAD

**Issue by Navaneeth-R-Krishnan** [JiyaGupta-cs/ShopNex#125]
I would like to enhance the pre existing UI in the  sign in page, and also add firebase authentication. 

Kindly assign this issue to me under GSSOC '24.

**Comment by Isha1233** [comment]
@Navaneeth-R-Krishnan kindly assign this task to me

**Comment by Sushilverma002** [comment]
@Navaneeth-R-Krishnan not required now.
