### ISSUE TITLE
Create Explore More Button On Women,Men  Products 

### ISSUE THREAD

**Issue by JiyaGupta-cs** [JiyaGupta-cs/ShopNex#13]
Add More Products to the Women, Men Products and it should display in sets of 12 every time the user clicks on the Explore More Button

![image](https://github.com/JiyaGupta-cs/ShopNex/assets/140608790/4f12204a-9873-4d21-b646-ecd9860bf37d)

**Comment by swetasingh8844** [comment]
@JiyaGupta-cs please assign this issue to me under JWOC'24

**Comment by JiyaGupta-cs** [comment]
Go ahead @swetasingh8844 
Make sure you follow contributing.md
