### ISSUE TITLE
Page is not fit to screen

### ISSUE THREAD

**Issue by SahithiDevalla** [JiyaGupta-cs/ShopNex#131]
The men and women section pages are not fit to layout, I can make the pages fit to the screen and correct the layout, I am a new contributor to GSSOC, Please assign this to me I can work on it.

**Comment by n14rishitha** [comment]
hi @JiyaGupta-cs 

I would like to work on this issue . so please assign this task to me under the label GSSoC'24

**Comment by Sushilverma002** [comment]
@SahithiDevalla not required... please work on some other issue.
