### ISSUE TITLE
Notifying the user when the product is added to the cart 

### ISSUE THREAD

**Issue by UjjwalGupta1105** [JiyaGupta-cs/ShopNex#134]
## Issue Description
When we are hitting the **Add to cart button** it is **not notifying the user** that the product is added to the cart .

## Steps to Reproduce
We Will showcase a message of "**Product added to  the cart**" whenever he/she add product to the cart .

## Expected Behavior
Whenever user adds an product to the cart , he/she will se a message on the screen of "Product added to  the cart" .

## Screenshots
![Screenshot 2024-05-10 164328](https://github.com/JiyaGupta-cs/ShopNex/assets/165131091/6a61c43e-ca1f-4df9-9f52-c06fce4ad381)

**Comment by Ech0Cipher** [comment]
Hey @UjjwalGupta1105 we have to add toast in this to show the notification . Can you assign me this so i can work on.

**Comment by Kbageja** [comment]
hi @JiyaGupta-cs  we can resolve this issue easily  by using react- hot-toast , kindly assign this issue to me . I would like to contribute on this
