### ISSUE TITLE
[Bug] : Fixing Subscribe Button Alignment

### ISSUE THREAD

**Issue by its-kumar-yash** [JiyaGupta-cs/ShopNex#136]
## Issue Description
I'll Fix Subscribe Button Alignment
Kindly assign this to me

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/97521394/db1ba14a-80fe-4bbf-b252-1b3f717de0fe)

**Comment by Isha1233** [comment]
@its-kumar-yash kindly assign this task to me

**Comment by kaiyumdev** [comment]
@JavidSumra Can you please review my code?

**Comment by mohit200008** [comment]
@JiyaGupta-cs  please assign this issue to me, i have fixed the alignment and now its correct. Made the pr for this with proper screenshots

**Comment by Aanya10Mishra** [comment]
Hi @JiyaGupta-cs ,
I'm Aanya Mishra, a GSSoC participant excited to contribute to your project. I came across the " Fixing Subscribe Button Alignment
" issue and believe my skills in Frontend align well. I'm eager to learn and contribute meaningfully. Would you consider assigning it to me?

**Comment by vaishnavip27** [comment]
Hey @JiyaGupta-cs I can work on this issue with a better styling button. Please assign me this issue. Looking forward for your approval
