### ISSUE TITLE
Adding responsiveness to the UI and hover effects

### ISSUE THREAD

**Issue by MandeyMan** [JiyaGupta-cs/ShopNex#14]
![Screenshot 2024-01-16 234932](https://github.com/JiyaGupta-cs/ShopNex/assets/120216011/d3d044b3-fe6a-4d60-8f87-f3b0b466f45a)

![Screenshot 2024-01-16 234916](https://github.com/JiyaGupta-cs/ShopNex/assets/120216011/6b2811d5-81db-4eb8-88f2-41531c688d8a)

![Screenshot 2024-01-16 234944](https://github.com/JiyaGupta-cs/ShopNex/assets/120216011/22afbf1d-d954-431b-9381-d11267ed05eb)

adding responsive features in website and adding more animation effects on buttons , card , navlinks and icons.

PLEASE assign me this issue  under  JWOC 2024.

**Comment by JiyaGupta-cs** [comment]
@MandeyMan An issue addressing the same concern has already been raised. But you can raise other issues

**Comment by JiyaGupta-cs** [comment]
@MandeyMan An issue related to responsiveness is already opened
