### ISSUE TITLE
improving the foorter 

### ISSUE THREAD

**Issue by Karansankhe** [JiyaGupta-cs/ShopNex#143]
## Issue Description
the footer is very simple

## Steps to Reproduce
improving it 
## Expected Behavior
[Describe what you expected to happen]

## Actual Behavior
[Describe what actually happened]

## Screenshots
[Include any relevant screenshots]

**Comment by Karansankhe** [comment]
please assign me these issue

**Comment by Harshitazz** [comment]
i can do this

**Comment by AMANVISHWAKARMA27** [comment]
@JiyaGupta-cs , kindly assign me the issue.

**Comment by MrCodYrohit** [comment]
👋 Hello there! As a contributor to GSSoC 2024, I'm eager to embark on my journey into the realm of open-source contributions. I'm keen to revamp your project's Readme Section, infusing it with user-friendliness and engagement. Would you kindly assign me this task? Also, could you specify the appropriate level for labeling purposes? Thanks for your time! 🚀

**Comment by Abhishek0732** [comment]
@JiyaGupta-cs please assign this issue to me I will improve the footer

**Comment by Jatingupta9120** [comment]
@JiyaGupta-cs  assign this issue to me

**Comment by Kbageja** [comment]
@JiyaGupta-cs  kindly assign this issue to me , I would like to contribute on it

**Comment by Sushilverma002** [comment]
@Karansankhe not required for now. please work on some other issue.
