### ISSUE TITLE
Add Hover Effects to Size Buttons

### ISSUE THREAD

**Issue by AtharvKasar04** [JiyaGupta-cs/ShopNex#144]
## Issue Description
Currently, the size buttons (S, M, L, etc.) on the product page lack hover effects, which diminishes the interactive and visual feedback for users. This issue aims to enhance the user experience by adding hover effects to these buttons. Upon hovering over each size option, the button should visually indicate its active state, providing users with clear feedback.

@JiyaGupta-cs Can you please assign this to me under GSSoC'24?
I can add interactive and minimal appealing hover effects for those specific buttons.
I'm interested to work on this issue.

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/108543702/ff0d351a-6a52-4afd-8a34-968a010b1e1c)

**Comment by Nayan-95** [comment]
Can you please assign me this issue.

**Comment by T1rth1** [comment]
i would like to work upon this issue..can you please assign me this issue?

**Comment by Jatingupta9120** [comment]
assign this  issue to me

**Comment by Aanya10Mishra** [comment]
Hi [Project Owner Name],

I'm Aanya Mishra, a passionate GSSoC participant eager to contribute to ShopNex site. The "adding of hover effect" issue caught my eye, and I believe my UI/UX skills can be a great asset. I'm a quick learner and excited to contribute meaningfully. Would you be open to assigning this to me?

**Comment by HimankPatidar** [comment]
i would like to work upon this issue. Can you please assign me this issue under GSSOC24

**Comment by Heena31** [comment]
Hey Niharika, I have participated in GSsoc'24 as a contributer. I would like to work on this issue. Kindly allow me to fix this.
