### ISSUE TITLE
subscribe button at email id is not synced

### ISSUE THREAD

**Issue by 20ankur07** [JiyaGupta-cs/ShopNex#152]
## Issue Description
subscribe button at email id section is going out of box which is not looking good.

## Steps to Reproduce
i can fix it

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/125962231/8acf6cf9-1100-42f2-94df-d27415cac857)

**Comment by 20ankur07** [comment]
Please assign this to me as I am a newcomer in open source contribution.

**Comment by 20ankur07** [comment]
@JiyaGupta-cs please assign this to me i can add hovering effects on it to make it more appealing.

**Comment by ivedmohan** [comment]
Dublicate Issue
