### ISSUE TITLE
Add Cross Button to Login/Signup Modal for Improved User Experience

### ISSUE THREAD

**Issue by Saksham2k3s** [JiyaGupta-cs/ShopNex#155]
## Issue Description
The modal in the login/signup section lacks a cross button for easy dismissal, causing inconvenience to users.

## Steps to Reproduce
1. Click to the login/signup button on the header.
2. Observe that there is no option to close the modal other than clicking outside of it.

## Expected Behavior
A cross button should be present in the modal window, allowing users to easily dismiss it without having to rely on clicking outside of the modal.

## Actual Behavior
The modal lacks a cross button, making it less intuitive for users to close it.

**Comment by Rohit153672** [comment]
hey i want to solve this issue can you please assign it to me

**Comment by Niharika0104** [comment]
@Saksham2k3s It's not a modal.Its is a page.So we cannot add cross button on it.Once please click on the button,then you will see that you are getting redirected to the login page and the url of the page changes.
