### ISSUE TITLE
Fix: The subscribe button is not properly placed.

### ISSUE THREAD

**Issue by souvik-maity** [JiyaGupta-cs/ShopNex#157]
## Issue Description
There is no margin between subscribe button and the outer box

## Steps to Reproduce
open the website and scroll down
## Expected Behavior
there should be proper margin between the subscribe button and the outer box. Also, the size of the subscribe button must be adjusted well.

## Screenshots
![Screenshot 2024-05-11 020917](https://github.com/JiyaGupta-cs/ShopNex/assets/145227417/897587de-90b0-487e-a419-e334b4ce1fa3)

**Comment by motuncoded** [comment]
Helo, I am currently a GSSOC contributor, kindly assign the issue to me

**Comment by souvik-maity** [comment]
Kindly assign this issue to me.Eagerly waiting to contribute .

**Comment by Kbageja** [comment]
hello @JiyaGupta-cs  kindly assign this issue to , I would like to contribute on it

**Comment by Ahmad102938** [comment]
hello Admin Please assign this issue to me under GSSoc24, I would like to wrok on it

**Comment by Ash19032005** [comment]
I'm a GSSoC's contributor. Kindly assign it to me

**Comment by ivedmohan** [comment]
#136 Dublicate issue
