### ISSUE TITLE
Functionality Issue: Removing One Item Removes All Items from Cart

### ISSUE THREAD

**Issue by divyanshahlawat** [JiyaGupta-cs/ShopNex#158]
Issue Description:
I'm encountering a critical functionality issue within our application's shopping cart feature. Specifically, when attempting to remove only one item from the cart, all items are unexpectedly being removed. This behavior deviates from the expected functionality and significantly impacts the user experience.
(Item should be of same categories)

Steps to Reproduce:

Add multiple items to the cart.
Navigate to the cart page.
Attempt to remove one specific item from the cart.
Observe that all items are removed instead of just the selected item.
Expected Behavior:
Upon removing one item from the cart, only the selected item should be removed, while the remaining items remain in the cart.

Actual Behavior:
Removing one item from the cart results in the removal of all items from the cart, which is not the intended behavior.
(Item should be of same categories)
Impact:

User Experience: This functionality issue disrupts the shopping experience for our users, causing frustration and potentially leading to abandoned carts.
Loss of Sales: Users may refrain from completing their purchases due to the inconvenience caused by this issue, resulting in a loss of potential sales.
Reputation: Inconsistent and faulty functionality reflects poorly on our application's reliability and may undermine user trust.
Proposed Solution:
To address this functionality issue, I propose the following steps:

Conduct a thorough investigation to identify the root cause of the problem.
Implement a fix to ensure that only the selected item is removed from the cart when prompted by the user.
Perform rigorous testing to validate the effectiveness of the fix and prevent regression.
Communicate the resolution to users and stakeholders, highlighting the improved shopping experience.
Additional Information:

Environment: [Specify the environment where the issue occurs, e.g., web, mobile app, specific browser or device.]
Screenshots or Videos: [Attach any relevant screenshots or videos demonstrating the issue, if applicable.]
Conclusion:
This functionality issue significantly impairs the usability of our application's shopping cart feature and warrants immediate attention. I urge the development team to prioritize the resolution of this issue to enhance the user experience and maintain our application's reputation for reliability.

Thank you for your attention to this matter. I'm available to provide further clarification or assistance as needed.

@JiyaGupta-cs  please assign me this issue under GSSOC

**Comment by aditya7483thakur** [comment]
Hello Sir ! please assigne me this issue.

**Comment by aditya7483thakur** [comment]
Hello Sir ! Please assigne me this issue

**Comment by Rishabh001pawar** [comment]
Hello mam,_ I am GSSOC contributor can you assign me this project_
