### ISSUE TITLE
Improving the Navbar

### ISSUE THREAD

**Issue by devu007** [JiyaGupta-cs/ShopNex#159]
## Issue Description
Improving the Header of Shopnex, Pop-up of words are not smooth

## Steps to Reproduce
I would like to fix this by aligning the words, decreasing the pop-up height, and smoothening the underline.

## Expected Behavior
It will become more smooth and the height of the pop-up will decrease as of now it's looking absurd.

## Screenshots
<img width="1440" alt="Screenshot 2024-05-11 at 8 42 59 AM" src="https://github.com/JiyaGupta-cs/ShopNex/assets/101053111/222dc992-5fae-45db-ad2a-71f1c2587550">

Please assign this issue to me.

**Comment by MOULYVINAYAKA** [comment]
Hello @devu007, Could you please assign this issue #159 to me? I am looking forward to working on it and contributing to the project's success

**Comment by Kbageja** [comment]
Hello @JiyaGupta-cs  , kindly assign this issue to me , I would like to contribute on it

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by EnchantedRepoRuler** [comment]
I would like to fix this issue
