### ISSUE TITLE
Converting Navbar to Sidebar when shrinking the site

### ISSUE THREAD

**Issue by devu007** [JiyaGupta-cs/ShopNex#160]
## Issue Description
Navbar when we shrink the site becomes disoriented.

## Steps to Reproduce
I can convert the Navbar into a Sidebar when we shrink the site or use it on mobile, it will look more elegant.

## Expected Behavior
When the site shrinks, the Navbar becomes the Sidebar.

## Screenshots
<img width="761" alt="image" src="https://github.com/JiyaGupta-cs/ShopNex/assets/101053111/3f75f5e4-5274-4ead-b8fa-edfd4fd9f054">

Please assign this issue to me, I can work on it as I have prior experience in it.

**Comment by MOULYVINAYAKA** [comment]
Hello @devu007, Could you please assign this issue to me under Gssoc'24? I am looking forward to working on it and contributing to the project's success.

**Comment by Kbageja** [comment]
I would like to contribute on this issue , this issue can be easily fixed with media queries and some styling please assign this to me

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by Amaaaaaaaan** [comment]
i can make this easily please assign me this

**Comment by nsk6704** [comment]
I kindly request you to assign this issue to me, an aspiring web developer certified by freeCodeCamp in Web Design and have also interned at a company named Codsoft.

Also I have contributed to roadmap.sh,
which is one of the most starred repository on GitHub!!

Here is my LinkedIn Profile for more information!

https://www.linkedin.com/in/saketh-kashyap-nagendra/
