### ISSUE TITLE
feature: adding hover effect 

### ISSUE THREAD

**Issue by solanki505** [JiyaGupta-cs/ShopNex#162]
## Issue Description
to make the page more interactive and catchy adding hover effect 

## Steps to Reproduce
using html and css I would add the hover effect.

## Actual Behavior
![Screenshot 2024-05-11 103525](https://github.com/JiyaGupta-cs/ShopNex/assets/158484284/8fead180-d6cd-4743-9c63-6f3ea232bbcc)
now the line below is not sliding

## Expected Behavior
it will hover below the text.

I would like to work on this , please assign me this under GSSOC'24

**Comment by DevNandini02** [comment]
please label the issue.

**Comment by DevNandini02** [comment]
I would like to work on this issue, please assign to me.

**Comment by Ahmad102938** [comment]
hello please label the issue I would like to work on it.

**Comment by Rish-tech1** [comment]
i would like to fix this issue

**Comment by gupta-ritik** [comment]
I would like to resolve the issue and also label the issue

**Comment by n14rishitha** [comment]
I would like to work on this issue . so please assign this task to me and Can u please label the issue as GSSoC'24

**Comment by Priyagohite** [comment]
I would like to resolve this issue please assign me to fix them.
