### ISSUE TITLE
[STYLE] Enhance the styling of navbar and home page

### ISSUE THREAD

**Issue by aryansharma220** [JiyaGupta-cs/ShopNex#165]
## Issue Description
The active position in navbar looks a bit odd and the font is also too big also the filter option needs some styling

## Steps to Reproduce
Go to the homepage to see the issues

## Expected Behavior
The navbar components should be styled better and font should be better
The filter drop down menu should be styled

## Actual Behavior
[Describe what actually happened]

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/133234867/bd6e5f64-bc76-43c0-8407-82f26e96e5fb)

![image](https://github.com/JiyaGupta-cs/ShopNex/assets/133234867/8f35d6cb-f909-4e00-bd64-efb1b54256aa)

Please assign it to me so that i can work on it

**Comment by jollyhub8278** [comment]
Hello team,
I'm eager to take on the challenge of enhancing the styling of both the navbar and the home page. I'll focus on refining the visual elements, optimizing layout and responsiveness, and ensuring a cohesive and polished appearance across devices.

With my experience in UI/UX design and front-end development, I'm confident I can elevate the aesthetic appeal and user experience of these crucial components. Here's my LinkedIn profile: https://www.linkedin.com/in/bharti-jangir-9a719a264/

Excited to tackle this task! Kindle please assign me this task @aryansharma220
