### ISSUE TITLE
Adding a 404 Page not found page 

### ISSUE THREAD

**Issue by Poushik11** [JiyaGupta-cs/ShopNex#168]
## Issue Description
[Provide a brief description of the issue]
If the url is not valid we will be directed to 404 not found page
## Steps to Reproduce
[Outline the steps required to reproduce the issue]

## Expected Behavior
[Describe what you expected to happen]

## Actual Behavior
[Describe what actually happened]

## Screenshots
[Include any relevant screenshots]
I would like to work on this , please assign me this under GSSOC'24

**Comment by r7projects-shayan** [comment]
@JiyaGupta-cs Kindly assign this issue to me, I have already started working on it

**Comment by n14rishitha** [comment]
@JiyaGupta-cs I would like to work on this issue . so please assign this task to me under the label  GSSoC24
