### ISSUE TITLE
Remove Duplicate product and fix the bug to of sort by button 

### ISSUE THREAD

**Issue by Pratik2401** [JiyaGupta-cs/ShopNex#174]
## Issue Description
No products in kids section and in women section duplicate products are shown when sortby is selected

## Steps to Reproduce
1.Go to womens section
2.sort by option select any option
3.observe the section

1.Go to kids section
2.No products are seen 

## Expected Behavior
1.Womens Section:-One product should be shown only once
2.No products in kids section
## Actual Behavior
1.When we select low to high or high to low in mens section the products didnt arrange themselves in the order  
2.In women section duplicate products are shown.

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/105542579/b49aaf90-ad28-4784-b329-7c381fb1ef27)
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/105542579/6143dfba-ae68-425c-a3ad-29e8ded99ef4)

**Comment by Pratik2401** [comment]
please assign me these issue @JiyaGupta-cs under GSSOC'24

**Comment by Manaswini123456** [comment]
Hello, I am a full stack developer with the required tech stack, kindly assign me with this issue under GSSOC'24 so that I can provide my insights and solutions.

**Comment by Sujitmaurya123** [comment]
@JiyaGupta-cs please assign this issues me

**Comment by Sushilverma002** [comment]
@Pratik2401 it just a sample of images which remain as it is.
