### ISSUE TITLE
fixing alignment of reviews with stars

### ISSUE THREAD

**Issue by sakshii00** [JiyaGupta-cs/ShopNex#177]
## Issue Description
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/92578876/9283b1a2-6a12-42db-95db-6670ffd4227e)

The number is not in alignment and looks off with the stars, I want to fix that.

Please assign me this as part of GSSOC'24

**Comment by aditya7483thakur** [comment]
Hello Mam ! Please assign me this issue under GSSOC 24

**Comment by Sandeep3jarma** [comment]
Hello Mam ! Please assign me this issue under GSSOC 24

**Comment by shweta-kush** [comment]
hello sir, please assign this issue to me. I have strong knowledge of flexbox, grid, and position. I think I am the right candidate to fix this issue.
