### ISSUE TITLE
Styling not applied on the sort by button

### ISSUE THREAD

**Issue by dwivedishrey** [JiyaGupta-cs/ShopNex#181]
![Screenshot 2024-05-11 195626](https://github.com/JiyaGupta-cs/ShopNex/assets/97790062/a63fb74f-252a-4447-bc29-ba11a301e014)

**Comment by dwivedishrey** [comment]
Please assign this issue to me

**Comment by Sujitmaurya123** [comment]
@JiyaGupta-cs please assign this issues me
