### ISSUE TITLE
Making explore more section responsive

### ISSUE THREAD

**Issue by Hacxmr** [JiyaGupta-cs/ShopNex#184]
## Issue Description
The "Explore More" section is currently empty and does not include any content.

## Steps to Reproduce
By utilizing HTML,CSS  and JS

## Expected Behavior
The "Explore More" section is empty, providing no additional content or value to users who reach that part of the website.

**Comment by harshit18-09** [comment]
I am a contributor in GSSOC 24 and it will interesting to make this explore more section responsive by adding some more features or may be improving its design.
It will be great if you assign me this issue @JiyaGupta-cs  under the tag of gssoc24.
Thanks 
Regards
