### ISSUE TITLE
Add hovering effect for login button 

### ISSUE THREAD

**Issue by reshamsai150** [JiyaGupta-cs/ShopNex#185]
With Hovering Effect:

Enhanced User Experience:
 Hover effects make the website feel more dynamic and responsive. Users appreciate small details like this, which contribute to a positive overall experience.

Accessibility: Properly designed hover effects can improve accessibility , assign this issue to me @JiyaGupta-cs

**Comment by Saksham1411** [comment]
As a GSsoc'24 contributor. I want to address this issue. I request you to assign this to me @reshamsai150

**Comment by Syed0206** [comment]
I want to work on this issue @JiyaGupta-cs  can you please assign me this issue under GSSOC'24

**Comment by Sushilverma002** [comment]
already assigned !!!!!!! please work on some other issue.
