### ISSUE TITLE
[Enhancement] Improving the gap between cards to make them similar

### ISSUE THREAD

**Issue by tanu-agarwal0101** [JiyaGupta-cs/ShopNex#188]
In one section there is a gap between the cards which is not present in others. I would like to work on this.
Please assign me to fix this under GSSOC'24.

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/162132053/86181121-5dc5-419a-8d66-32efeaa0e4e9)

![image](https://github.com/JiyaGupta-cs/ShopNex/assets/162132053/96dbfca5-431e-4b71-a3c6-cb8b68fe7b6b)

**Comment by Sooraj002** [comment]
Hey, I am a gssoc contributor, I would be happy to Fix this Issue

**Comment by aditya7483thakur** [comment]
Hello Mam ! Please assign me this issue under GSSOC 24

**Comment by tyagismriti** [comment]
I am interested to work on this issue please assigned to me under GSSOC 24

**Comment by tyagismriti** [comment]
I am interested to work on this issue please assigned to me under GSSOC 24
