### ISSUE TITLE
Dark and Light theme

### ISSUE THREAD

**Issue by Syed0206** [JiyaGupta-cs/ShopNex#189]
I would like to add dark and light theme to the website @JiyaGupta-cs can you please assign me this issue under GSSOC'24

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Please assign me this !

**Comment by Priyagohite** [comment]
I would like to work on the issue can you please assign me this to add dark and light theme to the website!!!

**Comment by gupta-ritik** [comment]
I would like to work on this issues.
please assign this issues to me

**Comment by tyagismriti** [comment]
I am interested to work on this issue .please assigned to me
