### ISSUE TITLE
To make the complete UI responsive

### ISSUE THREAD

**Issue by psychic-coder** [JiyaGupta-cs/ShopNex#191]
## Issue Description
The current website is not completely responsive and gives a poor user experince.

## Steps to Reproduce
I will use my knowledge of tailwind , bootstrap and libraries to improve the user experience.

## Expected Behavior
Complete responsiveness of the website.

## Actual Behavior
Poor UI and less responsiveness.

## Screenshots
<img width="550" alt="Screenshot 2024-05-12 at 3 30 48 AM" src="https://github.com/JiyaGupta-cs/ShopNex/assets/134062997/58576fa5-503e-4860-b990-20f2904bf59d">
<img width="563" alt="Screenshot 2024-05-12 at 3 30 54 AM" src="https://github.com/JiyaGupta-cs/ShopNex/assets/134062997/c9964c10-55c9-420e-b8c7-ca4c68354670">
<img width="569" alt="Screenshot 2024-05-12 at 3 31 02 AM" src="https://github.com/JiyaGupta-cs/ShopNex/assets/134062997/7f265f3d-2048-4992-a5e8-8b3ce5b30e6a">

**Comment by mukulpythondev** [comment]
@psykat1116  I wanna work on it.

**Comment by Sooraj002** [comment]
Hey, I am a gssoc contributor, I have previously made resposive website, I would be happy to Fix this Issue.
