### ISSUE TITLE
rating of each product

### ISSUE THREAD

**Issue by manjit-hub** [JiyaGupta-cs/ShopNex#192]
## Issue Description
Here Products have only price and number of sold quantity is mentioned. It would be better to add rating(stars) on each product. Which plays an important role for a buyer to judge the product quality. 

## Steps to Reproduce
I will add stars from FontAwesome and them on html and css file.

## Expected Behavior
It will be visible under each products.

**Comment by devSharma14** [comment]
I can perform this task. Please assign it to me. Thanks.

**Comment by manjit-hub** [comment]
Please assign this task to me

**Comment by Sushilverma002** [comment]
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/114687502/0411d5ac-5287-47dc-aa2c-49eebdc547e7)
at the marked position add star and reviews which is shown when u open any product

**Comment by manjit-hub** [comment]
Thankyou for giving me this opportunity to add some value to this project.
