### ISSUE TITLE
To add dynamic Copyright

### ISSUE THREAD

**Issue by Saimanjari777** [JiyaGupta-cs/ShopNex#193]
## Issue Description
The dynamic copyright is missing. 

## Expected Behavior
To have present year in the copyright

## Actual Behavior
It is displaying 2023 as the year which can be fixed.

I am working under GSSCOC'24.
Please assign this task to me.

**Comment by sumeet05xcaliber** [comment]
Can you assign this task to me under GSSOC24 , i am pretty sure i can complete it as early as possible.
