### ISSUE TITLE
Improving the UI of navigation bar ( Login button ,shop menu, Dark mode toggle ) #gssoc24

### ISSUE THREAD

**Issue by AnandK-pm** [JiyaGupta-cs/ShopNex#197]
Currently some of the menus in the navigation bar looks out of place (Like the shop menu) .
Things i intend to improve are :
* Aligning the menus perfectly
* Adding hover effect to the login button
* Improving the style of dark mode toggle so that it doesn't look out of place

Please assign me this task so that i can work on these issues to ensure a user friendly experience for your website. 
As a GSSoC '24 contributor and a candidate who have made lot of HTML and CSS projects , I'm confident that i can pull off this task efficiently.

![Screenshot 2024-05-12 113555](https://github.com/JiyaGupta-cs/ShopNex/assets/142206618/573a563b-20ae-470d-bd96-57de025f9782)

**Comment by shristipandey128** [comment]
@AnandK-pm please assign me this issue

**Comment by Sushilverma002** [comment]
already assigned... please work on some other issue.
