### ISSUE TITLE
Adding functionality to the Latest collections Button #gssoc24

### ISSUE THREAD

**Issue by AnandK-pm** [JiyaGupta-cs/ShopNex#198]
Currently the button has no functionality as it doesn't actually points to the latest collections in the website.
I intend to add a functionality to he button , also with a hover effect.

Please assign me this task so that i can work on these issue to ensure a user friendly experience for your website.
As a GSSoC '24 contributor and a candidate who have made lot of HTML and CSS projects , I'm confident that i can pull off this task efficiently.

![Screenshot 2024-05-12 114135](https://github.com/JiyaGupta-cs/ShopNex/assets/142206618/010568ca-151a-46ad-91d4-50a068ddc1ae)

**Comment by shristipandey128** [comment]
@AnandK-pm please assign me this issue

**Comment by vaishnavip27** [comment]
Hey, I have a lot of experience writing html, Css and Javascript. I can work on this issue very confidently. Please assign me this issue
