### ISSUE TITLE
improve the footer section 

### ISSUE THREAD

**Issue by MandeyMan** [JiyaGupta-cs/ShopNex#20]
![Screenshot 2024-01-18 002310](https://github.com/JiyaGupta-cs/ShopNex/assets/120216011/687aed9c-4434-4e78-a74e-cba2a701c362)

Adding more style and hover effects with proper links

please assign me this issue under jwoc 2024

**Comment by vishal2005025** [comment]
I have read the issue and I would like to work on the footer section of the homepage.
please assign me this issue under JWOC'2024

**Comment by JiyaGupta-cs** [comment]
@MandeyMan 
That's a good idea
But the website currently is not having these many pages to link with
