### ISSUE TITLE
Improve Animation for Dark/Light Mode Switch

### ISSUE THREAD

**Issue by thevijayshankersharma** [JiyaGupta-cs/ShopNex#201]
Issue Description
The animation for switching between dark and light modes needs improvement to enhance user experience and aesthetics.

Steps to Reproduce
Navigate to the settings or preferences section.
Locate the option to toggle between dark and light modes.
Toggle the switch to change between modes.
Expected Behavior
The transition between dark and light modes should be smooth and visually appealing, providing a seamless experience for the user.

Actual Behavior
Currently, the animation lacks finesse and may appear abrupt or jarring to users. It does not effectively convey the transition between modes and may detract from the overall user experience.

**Comment by thevijayshankersharma** [comment]
@JiyaGupta-cs I would like to work on this issue under GSsoC'24

**Comment by Shubham-Zone** [comment]
i would like to contribute to this issue... kindly assign me i am GSSOC'24 contributor

**Comment by Sushilverma002** [comment]
already assigned... please work on some other issue.

**Comment by thevijayshankersharma** [comment]
@Sushilverma002 I wanted to add animation to current toggle.
