### ISSUE TITLE
Not at all responsive

### ISSUE THREAD

**Issue by sharmi4590** [JiyaGupta-cs/ShopNex#202]
Hey @JiyaGupta-cs 
## Issue Description
The following website is not at all responsive.

## Steps to Reproduce
I will add media queries and other features of bootstrap as well to make it more responsive

## Expected Behavior
After using appropriate css and Bootstrap we can get the whole website responsive to use in any device

## Actual Behavior
While inspecting the webpage I got to know that it only worked for the particular dimension.

## Screenshots
![Screenshot (363)](https://github.com/JiyaGupta-cs/ShopNex/assets/102676949/e6f492f6-e73c-45ee-9930-8b01bc12e319)
Here's your webpage on inspecting.

**Comment by tishubohra** [comment]
Please assign me this issue

**Comment by Sushilverma002** [comment]
already assigned... please work on some other issue.
