### ISSUE TITLE
Label issues as GSSoC 24

### ISSUE THREAD

**Issue by SuhainaFathimaM** [JiyaGupta-cs/ShopNex#206]
## Issue Description
[Provide a brief description of the issue]

## Steps to Reproduce
[Outline the steps required to reproduce the issue]

## Expected Behavior
[Describe what you expected to happen]

## Actual Behavior
[Describe what actually happened]

## Screenshots
[Include any relevant screenshots]

**Comment by jainaman78** [comment]
There are some labels and tags missing in your issues. I'm eager to contribute to your project through GSSOC. Could you please assign me issue

**Comment by Tushar9352** [comment]
@JiyaGupta-cs  I would like to contribute on this project please assign this issue to me. I am very thankful to you.

**Comment by ivedmohan** [comment]
There are a lot of issues created we have to check every issue whether it's not a dublicate issue or something which might not be needed and few issues are needed to be discussed with Jiya. Please be patience we will do the things slowly. Thankyou
