### ISSUE TITLE
Issue with the drop down

### ISSUE THREAD

**Issue by Heena31** [JiyaGupta-cs/ShopNex#208]
In the website the drop down design is not looking good. UI should be attractive. Kindly Assign this issue to me. I can fix this
## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/79543358/5cc0ac2a-03eb-43ad-bfa8-15d532976ead)

**Comment by Utkarsh7368** [comment]
Please assign this issue to me. I am Contributor at GSSOC'24

**Comment by Sushilverma002** [comment]
already assigned... please work on some other issue.
