### ISSUE TITLE
responsive device

### ISSUE THREAD

**Issue by Varsani2520** [JiyaGupta-cs/ShopNex#216]
in responsive device look like this :
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/137641079/9dde49a2-7a3d-4043-b2bd-0c085ef7cc76)
@amanswarnakar

**Comment by tejjhode** [comment]
I am able to make changes please assign me under GSSOC'24

**Comment by Sushilverma002** [comment]
already assigned... please work on some other issue.
