### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Lak26** [JiyaGupta-cs/ShopNex#218]
The Favicon in not added on the website,it should be same as the logo is.
![favicon](https://github.com/JiyaGupta-cs/ShopNex/assets/156768505/b19926f4-4340-4dbf-915f-7e33c96effb1)
As the favicon of git hub is there but there is react symbol favicon present in shopNex website so that should be corrected with the image of logo.

**Comment by nishant0708** [comment]
hey i can fix this issue

**Comment by Lak26** [comment]
I can fix the issue of favicon.

**Comment by Lak26** [comment]
Please assign it to me.

**Comment by Sushilverma002** [comment]
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/114687502/f8436577-7fa1-489d-a3c3-34c872f48708)
already there !!
