### ISSUE TITLE
Social media icons do not redirect to any related profile

### ISSUE THREAD

**Issue by pruthviraj-desale** [JiyaGupta-cs/ShopNex#224]
## Issue Description
[The social media icons do not redirect to the respective pages upon clicking, and are unresponsive on clicking]

## Steps to Reproduce
[clicks on the social media tags and the icons do not give any response]

## Expected Behavior
[The expected behavior is that they they should redirect to their respective social media pages]

## Actual Behavior
[nothing occurs and the page remains the same upon multiple clicks]

## Screenshots
![image_2024-05-14_122534904](https://github.com/JiyaGupta-cs/ShopNex/assets/132280572/3a3b1c2d-3007-4322-8d60-b4ecdba7f0d2)

**Comment by pruthviraj-desale** [comment]
@JiyaGupta-cs  please assign this issue to me, i am GSSoC'24 contributor

**Comment by Ramben0909** [comment]
hey @JiyaGupta-cs can you please level the issue

**Comment by Sushilverma002** [comment]
not require for now.
