### ISSUE TITLE
 clicking a navbar button, observed that the button scrolls excessively upward

### ISSUE THREAD

**Issue by SAURABHVERMA00** [JiyaGupta-cs/ShopNex#227]
## Issue Description
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/115395946/83586e5b-d47b-4cd2-bf3e-a02b1abaeb8b)
Upon clicking a navbar button, we have observed that the button scrolls excessively upward, resulting in a less-than-ideal user experience. To enhance user navigation and ensure a smoother transition between sections, we propose implementing a zoom-in effect instead of the current upward scroll when a navbar button is clicked.

**Comment by ivedmohan** [comment]
Dublicate issue. SImilar issue and PR has been already created. 
@SAURABHVERMA00 you can try creating different issue which is not been created yet. Thankyou

**Comment by SAURABHVERMA00** [comment]
ok thanyou
