### ISSUE TITLE
Add to cart issue

### ISSUE THREAD

**Issue by siddxharth1** [JiyaGupta-cs/ShopNex#233]
## Issue Description
When i add a item in cart and again add the same item in the cart it is not incrementing the cart count correctly

## Steps to Reproduce
[Outline the steps required to reproduce the issue]

## Expected Behavior
[Describe what you expected to happen]

## Actual Behavior
[Describe what actually happened]

## Screenshots
Add 1 item:
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/91618085/8440a2f2-6c4c-4ad6-850b-fc6b384ba4e2)

Added 4 more item
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/91618085/cd5289b7-e191-4e33-8a7a-c2fdbecbd6a5)

Added 2 more item
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/91618085/2d84ad2a-2690-43b4-8a8a-f002e2c4a90b)

it is not correctly incrementing the value of the cart 
I would like to fix this issue under gssoc can you please assign it to me

**Comment by amanp18** [comment]
Hey could you please assign these project to me under gssoc'24.
