### ISSUE TITLE
Kids section empty 

### ISSUE THREAD

**Issue by hritika2409** [JiyaGupta-cs/ShopNex#234]
<img width="953" alt="image" src="https://github.com/JiyaGupta-cs/ShopNex/assets/117531823/74ab589d-0b9f-464c-8b6d-f6c0e0e27a2d">
The kid section is empty.Its not showing any images or product

Can i help you with this.Assign me as a contributor under GSsoc'24

**Comment by BhumikaRahwani** [comment]
Hi!! @JiyaGupta-cs . I am Bhumika Rahwani, contributor in GSSoC'24 . I would like to address this issue. Plz do assign me this.

**Comment by ShahHetviIT** [comment]
Hello @JiyaGupta-cs,
I m contributer at GSSoC 2024.
I want to fix this issue. Please assign me this.

**Comment by n14rishitha** [comment]
Hi @JiyaGupta-cs 
Im a Contributor at GirlScript Summer of code 2024.
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3

**Comment by Sushilverma002** [comment]
already assigned. please work on some other issue.
