### ISSUE TITLE
 #BUG Improve Visibility of Newsletter Input Box

### ISSUE THREAD

**Issue by ramith-kulal** [JiyaGupta-cs/ShopNex#24]
# Issue Description
The "Subscribe to Our Newsletter" email input box is currently not clearly visible, and users might miss it due to its current styling.

## Steps to Reproduce

1. Visit the page.
2. Scroll down to the "Subscribe to Our Newsletter" section.
3. Observe that the email input box is not easily noticeable.

## Expected Behavior

The email input box should be prominently displayed, and its styling  should be adjusted to ensure users can easily locate  it.

## Screenshot
![Screenshot 2024-01-18 220852](https://github.com/JiyaGupta-cs/ShopNex/assets/142984776/4cb311bd-7f2c-4995-8d8a-57fcddaff185)

I would like to work on this.

**Working under JWoC'24**

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal This issue is already solved , Look for other issues
