### ISSUE TITLE
Adding Hover effects and links to WhatsApp , Instagram , Pinterest.

### ISSUE THREAD

**Issue by n14rishitha** [JiyaGupta-cs/ShopNex#241]
## Issue Description
There is no hover over them . if we click on to it there are not responsive .And  would like to work on the Explore more button  to make it more Responsive and attractive.

## Screenshots
![Screenshot 2024-05-15 155720](https://github.com/JiyaGupta-cs/ShopNex/assets/153157112/1dfc3af7-0f57-4db4-8143-2c211c71d309)

**Comment by n14rishitha** [comment]
hi @JiyaGupta-cs 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3

**Comment by Dhevamuthu** [comment]
I would like to work for this issue as I hope will definitely solve this issue.
can u please assign this task for me under GSSOC 2024..

**Comment by ivedmohan** [comment]
This issue has been already created and assigned . @n14rishitha you can create another issue which hasen't been created we will assign it to you. Thankyou
