### ISSUE TITLE
Email validation and subscribe button not working

### ISSUE THREAD

**Issue by Amruta7203** [JiyaGupta-cs/ShopNex#244]
## Issue Description
Email is not getting accepted. Subscribe button is not properly aligned and not working.

## Steps to Reproduce
Adding Email validation - it should accept only globally accepted domains like .com, .org, etc. 
After clicking the subscribe button - pop up [subscribed!]

## Expected Behavior
Adding Email validation - it should accept only globally accepted domains like .com, .org, etc. 
After clicking the subscribe button - pop up [subscribed!]
It should be dynamic.

## Actual Behavior
No action is taken when email is entered and subscribe button is clicked.

## Screenshots
<img width="890" alt="image" src="https://github.com/JiyaGupta-cs/ShopNex/assets/116087736/e6a361bf-7d3a-432d-b0ef-c70cf0a69405">

**Comment by Amruta7203** [comment]
@JiyaGupta-cs Assign this issue to me under GSSOC'24. I want to work on it.

**Comment by ivedmohan** [comment]
@Amruta7203  Email validation has been already given to someone I would suggest if you could just work on creating pop up when subscribed. Thankyou

**Comment by Amruta7203** [comment]
Sure @ivedmohan! Please add label for Gssoc level for this issue.
