### ISSUE TITLE
Year in footer needs to update dynamic 

### ISSUE THREAD

**Issue by kapilG0** [JiyaGupta-cs/ShopNex#248]
## Issue Description
Year in footer should update dynamic 

## Steps to Reproduce
[Outline the steps required to reproduce the issue]

## Expected Behavior
[Describe what you expected to happen]

## Actual Behavior
[Describe what actually happened]

## Screenshots

![Screenshot_20240515_221347](https://github.com/JiyaGupta-cs/ShopNex/assets/59639410/f84385bd-bc1d-4458-949f-ca62b694a94e)

**Comment by Sushilverma002** [comment]
already assigned please work on some other issue.

**Comment by kapilG0** [comment]
> already assigned please work on some other issue.

Ok
