### ISSUE TITLE
{feat} : Adding cursor pointer to "Latest Collection" 

### ISSUE THREAD

**Issue by devlohani99** [JiyaGupta-cs/ShopNex#253]
## Issue Description
There is no cursor pointer effect when our cursor is over it , after adding the effect it will enhances the user experience

## Steps to Reproduce
Adding CSS code for cursor pointer

## Expected Behavior
Here Latest collection acts like the button or some link but when the user move its cursor over it it just came blank

## Actual Behavior
cursor pointer should came

## Screenshots
![Screenshot 2024-05-16 015210](https://github.com/JiyaGupta-cs/ShopNex/assets/142163543/3148856e-ea6f-498e-ab94-c7c1384ef890)

**Comment by devlohani99** [comment]
@JiyaGupta-cs  @Sushilverma002  @sudhanshu-77 Kindly assign me under GSSOC24

**Comment by Vansh-Choudhary** [comment]
This is not an issue, already present in the website.

**Comment by amanswarnakar** [comment]
Hello @devlohani99, I am not the owner of this repository. Please contact @JiyaGupta-cs.
