### ISSUE TITLE
responsiveness of the page and footer

### ISSUE THREAD

**Issue by jayanththalla** [JiyaGupta-cs/ShopNex#254]
cards are not good, and alignment of the cards are not responsiveness . subscribe button is to be hover and padding should be correct . footer of the page add more social  media links and other sections

**Comment by vansh-attri** [comment]
Hi, If anyone is not working on this issue. Can you please assign it to me?

**Comment by ivedmohan** [comment]
Hey @jayanththalla all these issues has already been created and assigned you can create other issues has not been created or can see if there is any issue which hasn't been assigned to anyone. Thankyou
