### ISSUE TITLE
BUG: Products Link in Footer Not Working

### ISSUE THREAD

**Issue by PranavKeshav24** [JiyaGupta-cs/ShopNex#272]
## Issue Description
The ‘Products’ link in the footer section is not working. When clicked, it does not lead to the Shop page.

## Steps to Reproduce
1. Go to the [website](https://shopnex.vercel.app/)
2. Scroll down to the footer.
3. Click on the ‘Products’ link.
4. Notice that the link does not lead to the expected page.

## Expected Behavior
When the ‘Products’ link in the footer is clicked, it should lead to the Shop page page.

## Actual Behavior
The ‘Products’ link in the footer does not lead to any page when clicked.

Please assign me this issue. I am a contributor for GSSoC’ 24. I would love to work on this issue.

**Comment by skrahmatullahgousi** [comment]
assign this issue sir

**Comment by Sanujkumar** [comment]
I will be resolve this issues, please assign this task to me

**Comment by ivedmohan** [comment]
Hey @PranavKeshav24 this issue has already been created #176 you can create some other issue. Thankyou
