### ISSUE TITLE
Footer Logo Not Redirecting to Home Page

### ISSUE THREAD

**Issue by PranavKeshav24** [JiyaGupta-cs/ShopNex#279]
## Issue Description
Clicking on the logo in the footer section does not lead to the home page. The logo is not functioning as a link.

## Steps to Reproduce
1. Go to the [website](https://shopnex.vercel.app/).
2. Scroll down to the footer section.
3. Click on the logo in the footer.

## Expected Behavior
The logo in the footer should function as a link to the home page. When clicked, it should redirect the user to the home page of the website.

## Actual Behavior
Nothing happens when the logo in the footer section is clicked. It does not redirect the user to the home page.

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/127531721/50ca13f0-4cdc-4983-b783-f556ecc3c5f5)

Please assign me this issue. I am a contributor for GSSoC’ 24. I would love to work on this issue.

**Comment by Tejsvapandey1** [comment]
could you please assign me this
