### ISSUE TITLE
Enhancement: Implement Customized Scrollbar.

### ISSUE THREAD

**Issue by ramith-kulal** [JiyaGupta-cs/ShopNex#28]
**Description:**
Enhance the visual appeal of our website by implementing a customized scrollbar. 

**Proposed Changes**
Customize the scrollbar appearance to match our website's theme.
Ensure the scrollbar is sleek and does not occupy unnecessary space.

### **Screenshots:**
**Current scrollbar:**
![Screenshot 2024-01-20 203030](https://github.com/JiyaGupta-cs/ShopNex/assets/142984776/88b61608-9e3d-4c28-9474-9b694f4fe674)
**Working under JWoC'24**

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal Go ahead

**Comment by sumit-kumar-jha1709** [comment]
@JiyaGupta-cs if this issue is not solved yet then please assign it to me under JWOC.
