### ISSUE TITLE
BUG: Page automatically switches to light mode even if it was previously set to dark mode

### ISSUE THREAD

**Issue by MrPC7** [JiyaGupta-cs/ShopNex#284]
**Issue Description**
When the page is refreshed, it automatically switches to light mode even if it was previously set to dark mode.

**Steps to Reproduce**
1. Open the web application.
2. Toggle the theme to dark mode.
3. Refresh the page.

**Expected Behavior**
The page should retain the dark mode setting after being refreshed.

**Actual Behavior**
The page reverts to light mode upon refresh, ignoring the previously set dark mode preference.

## Solution Description
Stored the theme preference in `localStorage` and ensured it is retrieved and applied on page load to maintain the selected mode after refresh.

_Assign me this issue under **GSSOC24**._

**Comment by Sooraj002** [comment]
I would like to resolve this issue.

**Comment by MrPC7** [comment]
@JiyaGupta-cs
