### ISSUE TITLE
BUG: Buttons are dummy on home screen

### ISSUE THREAD

**Issue by dhruv8433** [JiyaGupta-cs/ShopNex#295]
@JiyaGupta-cs 
## Issue Description
[Provide a brief description of the issue]
- when we click on banner button or explore buttons there is nothing happen

## Steps to Reproduce
[Outline the steps required to reproduce the issue]
- we can create another route or seperate page for particular button

## Expected Behavior
[Describe what you expected to happen]
- we can redirect to explore page 

## Actual Behavior
[Describe what actually happened]
- nothing happen when i click on "explore now" button

## Screenshots
[Include any relevant screenshots]
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/114583978/9ddfcdfb-7d8d-4de0-b66f-207caa14f512)

**Comment by Vansh-Choudhary** [comment]
fix this quickly

**Comment by dhruv8433** [comment]
@Vansh-Choudhary  Thank you

**Comment by Vansh-Choudhary** [comment]
i'll approve this pr and merge it but create another issue and start working on making the collections and offers page. tag me there and i'll assign you that issue.

**Comment by dhruv8433** [comment]
@Vansh-Choudhary Sure Thank you
