### ISSUE TITLE
Add Scroll Up Button

### ISSUE THREAD

**Issue by psykat1116** [JiyaGupta-cs/ShopNex#3]
The Images Are Overflowing From the Page.<br/> Please Assign Me For This to fix the bug and add a scroll-up button Under **JWOC 2024.**

**Comment by pranjal12-web** [comment]
Please Assign this issue to me Under JWOC 2024.

**Comment by JiyaGupta-cs** [comment]
@psykat1116 
Can you please attach the screenshots to make the description clear

**Comment by JiyaGupta-cs** [comment]
@psykat1116 Go ahead
