### ISSUE TITLE
BUG:Logo is not linked with home page

### ISSUE THREAD

**Issue by rahat2134** [JiyaGupta-cs/ShopNex#30]
Describe the bug
The logo on the website is currently not linked to the home page
<img width="342" alt="Screenshot 2024-01-21 at 12 28 36 AM" src="https://github.com/JiyaGupta-cs/ShopNex/assets/136263179/2b88788b-e3ee-4d69-a4ee-b4e79cbf66ae">

Expected behavior
Clicking on the logo should navigate the user to the home page of the website.

Additional Context (Mandatory )
This issue solution will make the nav bar most ideal.
Are you contributing under any open-source program ?
Yes, under JWOC.

**Comment by rahat2134** [comment]
@JiyaGupta-cs assign this to me under jwoc.

**Comment by JiyaGupta-cs** [comment]
@rahat2134 Assigning it to you

**Comment by rahat2134** [comment]
@JiyaGupta-cs thanks

**Comment by vishal2005025** [comment]
I would like to work on this issue.
PLEASE assign it to me under JWOC'2024
