### ISSUE TITLE
Subscribe button position and hover effect

### ISSUE THREAD

**Issue by ananya-sh30** [JiyaGupta-cs/ShopNex#301]
## Issue Description
The position of the subscribe button in the subscribe to newsletter section needs to be fixed. 

## Expected Behavior
We can move the button below the email section and also add a hover effect 

## Screenshots
![Screenshot 2024-05-17 232540](https://github.com/JiyaGupta-cs/ShopNex/assets/142817946/56919bae-023b-41c3-972d-d7bd40396a32)

Please assign this issue to me with gssoc labels

**Comment by Vansh-Choudhary** [comment]
already fixed
