### ISSUE TITLE
BUG : Social Media Link not responding 

### ISSUE THREAD

**Issue by ManasiDhotkar** [JiyaGupta-cs/ShopNex#303]
## Issue Description
When clicking on the social media icon, it does not respond to the social media page

## Expected Behavior
On clicking on a social media icon , it should take you to the intended social media page

## Screenshots
<img width="427" alt="image" src="https://github.com/JiyaGupta-cs/ShopNex/assets/99855497/0de4ad52-def2-43b2-9f6b-eb063a2944d6">

## Screen Recording 
https://github.com/JiyaGupta-cs/ShopNex/assets/99855497/4f823c7c-963e-4a94-b062-7bafa088fa51

**Comment by 8deepakkumar8** [comment]
@ManasiDhotkar pls assign this task to me.
also pls label this.
