### ISSUE TITLE
[Bug] Home page not responsive

### ISSUE THREAD

**Issue by pankaj-bind** [JiyaGupta-cs/ShopNex#323]
## Issue Description
When you reduce screen size you will see that page is not responsive.

## Expected Behavior
The background behind the girl must responsive when screen width reduces. 

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/73558583/28651cfc-f1c9-4f54-aa50-7e09eb18f76c)

**Comment by Sooraj002** [comment]
i would like to fix this issue
.

**Comment by Vansh-Choudhary** [comment]
issue already exists.
