### ISSUE TITLE
Security issues while installing node pakages

### ISSUE THREAD

**Issue by Sooraj002** [JiyaGupta-cs/ShopNex#324]
## Issue Description

while installing required node modules many vulnerabilities are found

## Steps to Reproduce
```node 
npm i``` 

## Expected Behavior
shows vulnerabilities
## Actual Behavior
[Describe what actually happened]

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/95868709/9ecadcd2-1e9d-48cc-9eec-ace702b25dd7)

**Comment by Sooraj002** [comment]
I would like to fix this issue . 
I am a gssoc contributor

**Comment by Vansh-Choudhary** [comment]
This is not an issue in the project, sometimes using older node modules and packages gives these warnings.
