### ISSUE TITLE
Footer Social media icon and home page sort button UI can be improved

### ISSUE THREAD

**Issue by Sooraj002** [JiyaGupta-cs/ShopNex#325]
## Issue Description
The icons in footer look bad, they have border , might be because u have used images

Edit: Also in home page sortby look bad 

## Steps to Reproduce
[Outline the steps required to reproduce the issue]

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/95868709/b87f9038-6388-4650-8996-0e411ec7b222)

![image](https://github.com/JiyaGupta-cs/ShopNex/assets/95868709/3a748ee5-c125-4b54-84f1-099b8670e203)

**Comment by Sooraj002** [comment]
I am a Gssoc Contributor , Please Assign me this issue i would like to help.

**Comment by Vansh-Choudhary** [comment]
I'm closing this issue, go and find another issue posted by someone else. Tag me there and I'll assign you.
