### ISSUE TITLE
About and contact us in footer on clicking doesn't scroll to top

### ISSUE THREAD

**Issue by sakshii00** [JiyaGupta-cs/ShopNex#339]
## Issue Description
When about and contact us in footer is clicked, it stays there and doesn't scroll to top.

## Video showing issue

https://github.com/JiyaGupta-cs/ShopNex/assets/92578876/1bfb39ee-99aa-4c65-b225-d16c8d12c4bd

## Steps to Reproduce
 I'd like to add the functionality for it to scroll to top when clicked.

**Comment by sakshii00** [comment]
@ivedmohan Please assign this to me

**Comment by Vansh-Choudhary** [comment]
@sakshii00 although the about and contact buttons sometimes works, but it should work perfectly. make it perfect.

**Comment by ParthNakum21** [comment]
Hello @Vansh-Choudhary and @JiyaGupta-cs, I'm interested in contributing to the project by improving the functionality of scroll to top. Could you please assign this task to me under GSSoC with appropriate level?

**Comment by sanjanasp786** [comment]
could you please assign this task to me under gssoc with appropriate level?

**Comment by Shubhamsingh2110** [comment]
i would like to work on it #339
