### ISSUE TITLE
[BUG FIX] Content Goes out of screen

### ISSUE THREAD

**Issue by rishicds** [JiyaGupta-cs/ShopNex#34]
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/124495375/6e489444-a72a-4a56-adcf-8f2fa246a53f)

At certain resolutions the content does not fix the screen, please assign it to me under JWOC'24 and I'll fix it

**Comment by JiyaGupta-cs** [comment]
An issue already exists concerning responsiveness.
