### ISSUE TITLE
Adding cursor pointer in Explore now in men page

### ISSUE THREAD

**Issue by devlohani99** [JiyaGupta-cs/ShopNex#343]
## Issue Description
Adding cursor pointer in Explore now in men page

## Steps to Reproduce
Adding css code

## Expected Behavior
cursor will come

## Actual Behavior
As a button its expected that the mouse cursor changes to pointer over it

## Screenshots
![Uploading Screenshot 2024-05-19 211817.png…]()

**Comment by devlohani99** [comment]
![Screenshot 2024-05-19 210055](https://github.com/JiyaGupta-cs/ShopNex/assets/142163543/18c1c0d5-b4e4-454c-b2dd-22b5a5e9ccc9)

**Comment by devlohani99** [comment]
@amanswarnakar @singhcodes26 @its-kumar-yash @psykat1116  kindly issue me under GSSOC24

**Comment by devlohani99** [comment]
![Screenshot 2024-05-19 211817](https://github.com/JiyaGupta-cs/ShopNex/assets/142163543/a6309e4f-4453-489d-aa44-11b021ea8aba)

**Comment by Vansh-Choudhary** [comment]
I just closed this issue and even gave you the proper reason. 
Why did you raised the same issue again ?

**Comment by devlohani99** [comment]
@Vansh-Choudhary tHERE IS NO CURSOR  POINTER IN EXPLORE MORE BUTTON TOO THAT WAYS

**Comment by Vansh-Choudhary** [comment]
That's not a button bro. That's just an image. Please think before posting an issue or PR. Don't randomly post anything.

**Comment by amanswarnakar** [comment]
Hello @devlohani99 , I am not the owner of this repository. Please contact @JiyaGupta-cs.
