### ISSUE TITLE
WEBSITE NOT RESPONSIVE

### ISSUE THREAD

**Issue by Venkatknight2295** [JiyaGupta-cs/ShopNex#347]
## Issue Description
[Provide a brief description of the issue]
WEBSITE IS NOT RESPONSIVE
## Steps to Reproduce
[Outline the steps required to reproduce the issue]

## Expected Behavior
[Describe what you expected to happen]
THE SIZE OF ELEMENTS SHOULD BECOME SMALL 
## Actual Behavior
[Describe what actually happened]
but the page is breaking out
## Screenshots
[Include any relevant screenshots]

![image](https://github.com/JiyaGupta-cs/ShopNex/assets/118790430/2f6dfb00-2676-4185-959d-e009d1a291b2)

**Comment by nhyadav05** [comment]
assign me this issue under gssoc24

**Comment by niteshbca** [comment]
@Venkatknight2295 please assign to me task.

**Comment by Venkatknight2295** [comment]
i amm looking to be assined i am also a contrubutor

**Comment by Venkatknight2295** [comment]
i am also a contrubutor

**Comment by Sushilverma002** [comment]
already assigned please work on some other issue.
