### ISSUE TITLE
[Bug]Kids Section doesn't show anything

### ISSUE THREAD

**Issue by rishicds** [JiyaGupta-cs/ShopNex#36]
![Screenshot_2024-01-22-16-43-37-46_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/JiyaGupta-cs/ShopNex/assets/124495375/2c730282-8365-4844-899f-fe288b2c52d6)

Please assign this issue to me under JWOC'24 and I'll fix it.

**Comment by JiyaGupta-cs** [comment]
An issue already exists concerning it
