### ISSUE TITLE
Add search feature

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [JiyaGupta-cs/ShopNex#378]
## Issue Description
I would like to enable users to search products based on keywords.

## Steps to Reproduce
1. Create search icon button in the nav near the cart.
2. By clicking on that button they will navigate to the seeach page.
3. There will be a search input as in the below screenshot.
4. Using that they can search items.
5. Search results will be shown under that.

## Expected Behavior
User can easily search products by key words.

## Actual Behavior
No search option

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/139672976/8267c1ea-9e4f-4216-84c5-7ac9836121f0)

@JiyaGupta-cs please kindly assign this issue to me for add this feature.

**Comment by Mansi-Raj** [comment]
Hello @JiyaGupta-cs 
I'm interested in this issue. So, please assign this to me
Thank you

**Comment by Burugupalli-Yogitha** [comment]
I am intrested in this issue, could you please assign this task to me

**Comment by Anmolgupta2004** [comment]
hello , I can solve this issue so please assign to me
