### ISSUE TITLE
Improving social media icons and adding hover effect 

### ISSUE THREAD

**Issue by SalehaTabassum** [JiyaGupta-cs/ShopNex#381]
Hello PA,
In footer the social media icons look so dull..
![Screenshot_2024-05-22-14-52-44-26_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/JiyaGupta-cs/ShopNex/assets/169278740/238bf806-8fb2-4483-adf6-f7d4dfa2e458)

It would make it look attractive if we add some hover effects to it .
@Vansh-Choudhary please assign this issue to me under GSSOC 2024 and add appropriate labels to it

**Comment by niteshbca** [comment]
@SalehaTabassum Please assign to me task and solve the problem.

**Comment by ParthNakum21** [comment]
@JiyaGupta-cs and @Vansh-Choudhary, Please reply.

**Comment by Sushilverma002** [comment]
already assigned, please work on some other issue.
