### ISSUE TITLE
Add "Privacy policy" and "terms and conditions" pages to the website 

### ISSUE THREAD

**Issue by MastanSayyad** [JiyaGupta-cs/ShopNex#384]
## Issue Description
Hey @JiyaGupta-cs I would like to add "Privacy Policy and Terms and Conditions" Pages for your website to make it more professional and more engaging

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/101971980/310c6c87-2143-4a79-a7e2-1cfef4af7f18)

@Vansh-Choudhary Could you pls assign this issue to me under gssoc24??

**Comment by Burugupalli-Yogitha** [comment]
Could you please assign this task to me

**Comment by MastanSayyad** [comment]
@JiyaGupta-cs  please take a look at this issue

**Comment by MastanSayyad** [comment]
@JiyaGupta-cs
