### ISSUE TITLE
Change the look of the product items

### ISSUE THREAD

**Issue by SadafKausar2025** [JiyaGupta-cs/ShopNex#387]
## Issue Description
I have changed the look of the item good

before
![Screenshot (1774)](https://github.com/JiyaGupta-cs/ShopNex/assets/137484958/669da8c7-27da-47ff-94ed-0815b1b9b6ea)

after

https://github.com/JiyaGupta-cs/ShopNex/assets/137484958/e4561446-68db-4019-bb32-6ee40d94eb0c

**Comment by SadafKausar2025** [comment]
I have change the look of the items and also given cursor pointer to it 
and now it look much better and good

**Comment by SadafKausar2025** [comment]
Hey @JiyaGupta-cs 

can you please assign me this issue

**Comment by Vansh-Choudhary** [comment]
Sorry but this is already done.
