### ISSUE TITLE
Home page needs to be responsive 

### ISSUE THREAD

**Issue by kapilG0** [JiyaGupta-cs/ShopNex#391]
## Issue Description
Content not displaying properly in mobile of home page 

## Steps to Reproduce
[Outline the steps required to reproduce the issue]

## Expected Behavior
[Describe what you expected to happen]

## Actual Behavior
[Describe what actually happened]

## Screenshots
![Screenshot_20240523_140405](https://github.com/JiyaGupta-cs/ShopNex/assets/59639410/62d6785c-2518-4d9a-bd3c-d29f22985f95)

**Comment by kapilG0** [comment]
Hello @JiyaGupta-cs please assign this issue to me under gssoc 24

**Comment by niteshbca** [comment]
@kapilG0 Please assign to me task and solve the problem.

**Comment by Sushilverma002** [comment]
already assigned
