### ISSUE TITLE
add hover effect on all buttons

### ISSUE THREAD

**Issue by kartikmehta18** [JiyaGupta-cs/ShopNex#392]
## Issue Description
i want want to add hover effect on all buttons which looks more good

## Screenshots
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/125860170/f2bbfd3d-2c4b-4d08-a52a-e2be8ac2c14a)

**Comment by Burugupalli-Yogitha** [comment]
@kartikmehta18 Can you please assign this task to me.

**Comment by Sushilverma002** [comment]
already assigned.
