### ISSUE TITLE
adding quantity feature and selcting size feature

### ISSUE THREAD

**Issue by Pranav-Rastogi1** [JiyaGupta-cs/ShopNex#4]
Assign me this under JWOC'24

**Comment by pranjal12-web** [comment]
hey @JiyaGupta-cs Please assign me this issue under JWoC'24

**Comment by JiyaGupta-cs** [comment]
@Pranav-Rastogi1 
Assigning you !!!!
Make sure you follow the contributing.md

**Comment by JiyaGupta-cs** [comment]
@Pranav-Rastogi1 Are you working on it?

**Comment by JavidSumra** [comment]
Hey @JiyaGupta-cs if No one is Working on this Issue I would Like To Work on This issue Under JWOC 2024

**Comment by JiyaGupta-cs** [comment]
@Pranav-Rastogi1 Unassigning you due to inactivity
@JavidSumra Assigning you

**Comment by JavidSumra** [comment]
Hey @JiyaGupta-cs Mam Please Close this issue as completed.
