### ISSUE TITLE
responsive screen 

### ISSUE THREAD

**Issue by Varsani2520** [JiyaGupta-cs/ShopNex#413]
## Issue Description
[Provide a brief description of the issue]
in responsive device layout is not perfect 

## Steps to Reproduce
[Outline the steps required to reproduce the issue]
fixed layout
apply container
apply grid

## Expected Behavior
[Describe what you expected to happen]
in mobile screen and full screen different different look

## Actual Behavior
[Describe what actually happened]

## Screenshots
[Include any relevant screenshots]

![image](https://github.com/JiyaGupta-cs/ShopNex/assets/137641079/9290137d-04aa-4dd1-ae94-a6a9b19b4886)

**Comment by Sushilverma002** [comment]
already assigned .
