### ISSUE TITLE
Addition of Facebook social icon 

### ISSUE THREAD

**Issue by shreya-paul-17** [JiyaGupta-cs/ShopNex#486]
## Issue Description
Addition of the Facebook icon can be done at the footer section

## Steps to Reproduce
Font awesome toolkit can be used in order to add the icon at the footer

## Expected Behavior
Facebook icon at the bottom

## Actual Behavior
No Facebook icon is present

## Screenshots
![shop-nex-2](https://github.com/JiyaGupta-cs/ShopNex/assets/135226069/cd7ddb8f-6847-44a2-95c5-8268a906ca78)

I am a GSSoC 2024 contributor
I agree to follow the Contributing guidelines
I agree to follow the Code of Conduct of the project
I am willing to work on this issue

**Comment by kashi-verma** [comment]
pls assign me this issue @JiyaGupta-cs . I'm willingly want to contribute in such kind of good  projects.
Thanks you
