### ISSUE TITLE
Want to improve the logo icon 

### ISSUE THREAD

**Issue by Arushi009** [JiyaGupta-cs/ShopNex#496]
## Issue Description- Want to improve the logo icon
[Provide a brief description of the issue]

## Steps to Reproduce-Actually i want to change the logos of Instagram, WhatsApp and Pinterest.We can change its icon and give it a gradient version.
[Outline the steps required to reproduce the issue]

## Screenshots
[Include any relevant screenshots]
![Screenshot 2024-06-07 163433](https://github.com/JiyaGupta-cs/ShopNex/assets/151595150/6c5cf008-6299-4132-bef4-8b13a0dce43b)

I am GSSOC Contributer 2024. This is my first project. Please assign this issue to me.

**Comment by Arushi009** [comment]
@JiyaGupta-cs Please assign me this issue as I'm UI/UX Designer and frontend developer.

**Comment by Sushilverma002** [comment]
please work on some other issue.
