### ISSUE TITLE
About/Contact

### ISSUE THREAD

**Issue by prasukjain07** [JiyaGupta-cs/ShopNex#5]
About and contact buttons in the end of the page are not working, we can improve them, by adding about and contact pages and redirect to that pages through these links

**Comment by prasukjain07** [comment]
> About and contact buttons in the end of the page are not working, we can improve them, by adding about and contact pages and redirect to that pages through these links
> 

JWOC

**Comment by JiyaGupta-cs** [comment]
@prasukjain07 Assigning you 
Make a beautiful About and Contact Page
Make sure follow the contributing.md

**Comment by prasukjain07** [comment]
@JiyaGupta-cs Please check my PR
