### ISSUE TITLE
Making website responsive

### ISSUE THREAD

**Issue by dhairyagothi** [JiyaGupta-cs/ShopNex#504]
I would like to make the website responsive ![Screenshot_20240611_180850.jpg](https://github.com/JiyaGupta-cs/ShopNex/assets/142989448/961d789c-5ab7-4c44-b40a-5bc591a21275)

Please assign this issue to me
@JiyaGupta-cs

**Comment by Vibha17** [comment]
Hi I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

**Comment by JiyaGupta-cs** [comment]
@dhairyagothi go ahead

**Comment by JiyaGupta-cs** [comment]
Try using tailwind css

**Comment by dhairyagothi** [comment]
Okay sure i will make a PR asap

**Comment by dhairyagothi** [comment]
please check the PR and merge it @JiyaGupta-cs

**Comment by dhairyagothi** [comment]
@JiyaGupta-cs mam please check the PR and merge it with label gssoc and level 3

**Comment by dhairyagothi** [comment]
please check the PR and merge it @JiyaGupta-cs

**Comment by dhairyagothi** [comment]
It is an Issue you have closed it as not planned 🤣
