### ISSUE TITLE
Adding Custom Cursor

### ISSUE THREAD

**Issue by chaanakyaaM** [JiyaGupta-cs/ShopNex#525]
## Issue Description
[Provide a brief description of the issue]

The website UI is awesome, but it can look more attractive and professional by adding an interactive custom cursor.

## Steps to Reproduce
[Outline the steps required to reproduce the issue]

I would like to add a custom interactive cursor instead of default cursor.

## Expected Behavior
[Describe what you expected to happen]

## Actual Behavior
[Describe what actually happened]

## Screenshots
[Include any relevant screenshots]

**Comment by SagarRathore1** [comment]
I would like to   cursor animation on this which will make this website more attractive and professional . this will shown like this :

![image](https://github.com/JiyaGupta-cs/ShopNex/assets/169483518/1b3a498d-b0f5-48ab-bc55-42b4ebb0d652)


https://github.com/JiyaGupta-cs/ShopNex/assets/169483518/5b77e232-737f-4f6f-9f27-fceb50a4c6e6
