### ISSUE TITLE
UI Enhancement : Footer of the Website

### ISSUE THREAD

**Issue by smilewithkhushi** [JiyaGupta-cs/ShopNex#54]
This issue involves creating a standard and ideal footer for the website.
The footer shall contain relevant information about the website, social links and other important links.

Reference : 
<img src="https://github.com/JiyaGupta-cs/ShopNex/assets/102166679/d931af00-e46c-45e2-94a5-ed877e431e74" width=400>

Would love to contribute to the project by working on this issue!

**Comment by JiyaGupta-cs** [comment]
Look for other major issues
