### ISSUE TITLE
Adding Hovering Effect To Social Media Icons in Footer

### ISSUE THREAD

**Issue by singhcodes26** [JiyaGupta-cs/ShopNex#6]
I can add links to instagram , pinterest and whatsapp . i can also add hovering effects to the icon for better results

**Comment by singhcodes26** [comment]
under JWOC'24

**Comment by SGCODEX** [comment]
I would like to work on this issue under JWOC

**Comment by ogshashwat17** [comment]
i want to work on this

**Comment by pranjal12-web** [comment]
Hey @JiyaGupta-cs ...Please assign me this issue under JWoC'24

**Comment by JiyaGupta-cs** [comment]
@singhcodes26 
Currently we are not having any social media page
So you can go ahead by adding hovering effects to it

**Comment by thatguywhocode** [comment]
Hey @JiyaGupta-cs , can you assign me this task under JWOC

**Comment by Divyanshgarg-04** [comment]
@JiyaGupta-cs I would love to work on this issue under JWOC. Can you please assign this issue to me
