### ISSUE TITLE
Select Quantity isn't visible properly

### ISSUE THREAD

**Issue by Bishal-35** [JiyaGupta-cs/ShopNex#60]
![Screenshot 2024-01-31 181038](https://github.com/JiyaGupta-cs/ShopNex/assets/120501312/cd7b79fa-a2ad-4324-ab02-918a0e580e8e)

on increasing or decreasing the quantity the amount isn't visible properly. I will fix it. Please assign it to me @JiyaGupta-cs

**Comment by satyam-mishra-07** [comment]
Please assign this issue to me under JWOC 2024

**Comment by JiyaGupta-cs** [comment]
@Bishal-35 Assigned
