### ISSUE TITLE
Social Media App Icons

### ISSUE THREAD

**Issue by madhurima316** [JiyaGupta-cs/ShopNex#62]
I would like to replace the social media app pictures of the footer section with icons and would add hover effects to them.

Please assign me this issue under JWOC 2024.

**Comment by JiyaGupta-cs** [comment]
@madhurima316 Assigned

**Comment by ramith-kulal** [comment]
if still open i would like to take this

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal Inspect , I think hover effects are already added to it

**Comment by ramith-kulal** [comment]
yeah hover effects are already done , how about replacing pictures with pngs ? ig we need to toggle between logo colors to match with the dark and light mode

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal 
Try other major issues
I'm closing this one
