### ISSUE TITLE
[BUG]: Fix Dark Mode

### ISSUE THREAD

**Issue by JiyaGupta-cs** [JiyaGupta-cs/ShopNex#67]
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/140608790/0457f250-b18c-4113-9f19-e88925635980)

Earlier it was not black in light mode
Make it with white background in light mode and black in dark

**Comment by Bishal-35** [comment]
I would like to work on it under **JWoC'24**

**Comment by JiyaGupta-cs** [comment]
@Bishal-35 assigned

**Comment by Bishal-35** [comment]
Can you please explain about the issue ?

**Comment by Bishal-35** [comment]
@JiyaGupta-cs Can you please explain about the issue as it seems okay in dark mode

**Comment by JiyaGupta-cs** [comment]
![image](https://github.com/JiyaGupta-cs/ShopNex/assets/140608790/5ff4e4d7-3de6-444f-b6ce-0582f6922231)

Earlier it was like this
