### ISSUE TITLE
Add GitHub Issue and PR Template

### ISSUE THREAD

**Issue by JiyaGupta-cs** [JiyaGupta-cs/ShopNex#69]
# Description
Add GitHub Issue and PR Template so that new comers can make issues and PR easily

**Comment by Anushkabh** [comment]
kindly assign me this under jwoc @JiyaGupta-cs

**Comment by Prithwi32** [comment]
@JiyaGupta-cs I would like to work on this issue under Jwoc

**Comment by JiyaGupta-cs** [comment]
@Anushkabh assigning you
@Prithwi32 you take up this one https://github.com/JiyaGupta-cs/mytwit/issues/70

**Comment by JiyaGupta-cs** [comment]
@Anushkabh Any update?

**Comment by Anushkabh** [comment]
i will push the changes by eod @JiyaGupta-cs

**Comment by Anushkabh** [comment]
kindly merge #74  if satisfied @JiyaGupta-cs
