### ISSUE TITLE
Add GitHub workflow greetings

### ISSUE THREAD

**Issue by JiyaGupta-cs** [JiyaGupta-cs/ShopNex#70]
# Description

Add GitHub workflow greetings so that new comers get a welcome message

**Comment by Anushkabh** [comment]
kindly assign me this under jwoc , I would like to work @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Anushkabh Assigning you

**Comment by Anushkabh** [comment]
kindly merge #83 if satisfied @JiyaGupta-cs
