### ISSUE TITLE
fix: Cursor Pointer - Explore More Button

### ISSUE THREAD

**Issue by JiyaGupta-cs** [JiyaGupta-cs/ShopNex#72]
# Description:-

Make Cursor Pointer On Explore More Button on All Pages

# Screenshot-

![image](https://github.com/JiyaGupta-cs/ShopNex/assets/140608790/d9bc087c-be04-4930-bd88-b62289df23b5)

**Comment by Anushkabh** [comment]
kindly assign under JWOC @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Anushkabh go ahead

**Comment by Anushkabh** [comment]
kindly merge #84 if satisfied @JiyaGupta-cs
