### ISSUE TITLE
feat: Beautify About US Page

### ISSUE THREAD

**Issue by JiyaGupta-cs** [JiyaGupta-cs/ShopNex#73]
# Description:-

Beautify About US Page According to the current theme of the website

# Screenshot:-

![image](https://github.com/JiyaGupta-cs/ShopNex/assets/140608790/2c8d5a8b-7a3e-485f-bd07-b7dc84a14966)

**Comment by HARSH00M** [comment]
I would like to work on it..

**Comment by JiyaGupta-cs** [comment]
@HARSH00M go ahead
