### ISSUE TITLE
FIX: Animation Issues for Instagram, Pinterest, and WhatsApp Logos on Hover

### ISSUE THREAD

**Issue by ramith-kulal** [JiyaGupta-cs/ShopNex#79]
## Issue Description

This issue addresses a bug in the animation applied to the Instagram, Pinterest, and WhatsApp logos when hovering over them.

## Actual Behavior
- Providing a visually appealing animation on hover.

## Screenshots
currently what it looks like:
https://github.com/JiyaGupta-cs/ShopNex/assets/142984776/29c4e778-6346-456a-a76a-8da390908161

**working under JWOC**

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal Go ahead
