### ISSUE TITLE
Beautify Contact US page

### ISSUE THREAD

**Issue by HARSH00M** [JiyaGupta-cs/ShopNex#82]
##Issue description - The contact us page need UI update.

##Screenshot - 
<img width="960" alt="image" src="https://github.com/JiyaGupta-cs/ShopNex/assets/115922494/ae5439f0-5fdd-49a7-9871-3ccfe1880832">

**Comment by JiyaGupta-cs** [comment]
It's already being resolved in another issue 
https://github.com/JiyaGupta-cs/ShopNex/pull/75
