### ISSUE TITLE
BUG: Cart Total Sum Calculation 

### ISSUE THREAD

**Issue by ramith-kulal** [JiyaGupta-cs/ShopNex#85]
## Issue Description

The total sum of cart items is not adding up correctly. Additionally, there are some other problems present in the cart functionality.
## Steps to Reproduce

Add multiple items to the cart.
Navigate to the cart page.
Review the total sum displayed.
## Expected Behavior

The total sum displayed in the cart should accurately reflect the combined prices of all items added to the cart.
## Actual Behavior

The total sum displayed in the cart does not accurately reflect the combined prices of all items added to the cart. Some items may not be included in the total, or the total sum may be incorrect.
## Screenshots

![Screenshot 2024-02-21 110017](https://github.com/JiyaGupta-cs/ShopNex/assets/142984776/d5085424-64bb-484f-b17b-dcdb2db9839c)
**Working under JWOC**

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal go ahead
Also resolve the quantity is not displaying in the screenshot
