### ISSUE TITLE
Updating the style of a section in homepage

### ISSUE THREAD

**Issue by MaruthiSingh** [JiyaGupta-cs/ShopNex#9]
I would like to work on the below section from homepage

![image](https://github.com/JiyaGupta-cs/ShopNex/assets/103304179/49e69c94-bcc1-4d01-af7f-b2a4b5fbd85c)

I would like to work on that issue under JWOC

**Comment by JiyaGupta-cs** [comment]
@MaruthiSingh
Go ahead and make sure you follow the contributing.md
Also ensure to make it according to the current template of the website including colors, etc.
